name: Deploy2

on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish NumberToWords/NumberToWords.csproj --configuration Release --output ./publish --runtime win-x86 --self-contained false -p:PublishTrimmed=false -p:PublishSingleFile=false

      - name: Test with .NET
        run: dotnet test

      - name: Deploy to Simply
        uses: talunzhang/auto-web-deploy@v1.0.1
        with:
          website-name: linda10-001-site1
          server-computer-name: https://win8128.site4now.net:8172
          server-username: linda10-001
          server-password: Linda@10
          target-delete: true
